### PR TITLE
added Atila

### PR DESCRIPTION
**Pull request by ademidun**

### CODE REVIEW

**Comment by matkoniecz** [comment]
It seems to be a really low quality aggregator.

I went to https://atila.ca/scholarship with https://atila.ca/scholarship/1000-unilever-voices-for-change-scholarship-ela1l382 listed as the top one: and it links to a closed page ( https://survey.alchemer-ca.com/s3/50135911/yconic-Unilever-Voices-for-Change )

It directs to https://forms.yconic.com/s/unilever-voices-for-change-award-2022/tt-9e7413 which is not even offering money as promised: but company scrip that can be spend only in "Unilever UShop".

**Comment by ademidun** [comment]
@matkoniecz Atila is much more than a "really low-quality aggregator".

Atila does two things:

1. [A platform that makes it easy for anyone to start a scholarship or grant](https://atila.ca/start)
2. [A search engine for scholarships and grants](https://atila.ca/scholarship) (this is the "really low-quality aggregator" piece that you are referring to)

The first part, a platform to start scholarships and grants, is the reason why I added it to this repo. You can see some examples of how people have used our platform to start scholarships and grants: 

1. [A Case Study on the Skateboards for Hope Scholarship](https://atila.ca/blog/llmercer/a-case-study-on-the-skateboards-for-hope-scholarship/) <- If you don't read any of the other links, read this one.
2. [Meet Atila’s First Scholarship Winners](https://atila.ca/blog/reesadayani/meet-atilas-first-scholarship-winners/)
4.  [Meet the Winners of the Ademidun 2021 Scholarships](https://atila.ca/blog/tomiwa/meet-the-winners-of-the-ademidun-2021-scholarships/)
5. [Alexis Lodge - Future of Care Nursing Scholarship](https://atila.ca/scholarship/alexis-lodge-future-of-care-scholarship-90pwh6u6)
6. [Things You Should Do When Creating a Scholarship or Grant](https://atila.ca/blog/tomiwa/things-you-should-do-when-creating-a-scholarship/)

I would really encourage both you @matkoniecz and @nayafia to browse those links. After you've perused those links, it will be clear how we're trying to make it easier for more people to create their own microgrants; so others can do their own version of [Nadia's giving away $5,000 on the internet ](https://medium.com/@nayafia/how-to-give-away-5-000-on-the-internet-66cae906ab7e).

Now, to your "really low-quality aggregator" aggregator comment. I agree with you. Partially.

The quality of the results in the search engine is a function of the scholarships and grants that other people create.

I agree with your point that the search engine part of Atila could be improved. In fact, I'm glad you pointed this out because it gives me some concrete examples I can use as a reference when fixing the recommendation algorithm. So thank you for that comment.

I work on this part-time while maintaining a full-time job so with the limited time I have, I've been prioritizing the scholarship and grants launchpad more than the search engine part.

The part of Atila that helps people start a scholarship or grant is a service that the types of people interested in this microgrants repo would also be interested in.

Thus, I would like to kindly ask @nayafia if you would consider reopening this pull request and merging it with the other resources.

**Comment by matkoniecz** [comment]
> browse those links

Tried, got hit with user hostile nag screen

screen

**Comment by ademidun** [comment]
Thanks for the response @matkoniecz .

I agree with you, popup nag screens are annoying and actually a UX dark pattern. I've been debating removing it for a while. Your comment is further proof that it might be more negative than positive. I will remove it.

So after I remove the popup screens will you add Atila?

If your answer is no, can you please provide an itemized list of things I should change in order to qualify for being added to this resource.

**Pull request closed without merging**
